# Generated by Django 6.1 on 2026-08-29 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietApp', '0004_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
